name: End-to-end tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
  - cron: "*/10 * * * *"
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chromium
          - firefox
          - edge

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress install
        run: npm i
      - name: output secret
        run: ${{ secrets.SECRET_PASSWORD}}
      - name: Cypress run
        uses: cypress-io/github-action@v6